/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ufo.glb --transform --types --keepmeshes 
Files: ufo.glb [896.9KB] > C:\PROJECTS\PORTFOLIO\3DModels\ufo-transformed.glb [62.02KB] (93%)
Author: stevespencer (https://sketchfab.com/stevespencer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-940ec24a2e4f4807ae862dfa6d7f6af9
Title: UFO
*/
"use client";

import * as THREE from 'three'
import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Canvas } from '@react-three/fiber';
import PostProcessingEffects from '../Effects';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Dome: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Engine_Blue: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

function Ufo(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ufo-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Dome} position={[0, 0.24, 0]} scale={2.406} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Black} scale={[4.348, 1, 4.348]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Engine_Blue} scale={[4.348, 1, 4.348]} />
    </group>
  )
}

export default () => (
  <Canvas
      orthographic
      camera={{
          position: [0, 0, 300],
      }}
  >
      <OrbitControls minDistance={101} maxDistance={1e4} dampingFactor={0.1} zoomSpeed={0} rotateSpeed={0.3} />
      <ambientLight intensity={0.3} />
      <directionalLight position={[0, 0, 10]} intensity={0.7} />
      <directionalLight position={[0, 0, -10]} intensity={0.7} />
      <PostProcessingEffects />
      <Suspense fallback={null}>
          <mesh scale={40} position={[0, 0, 0]} rotation={[0, 0, 0]}>
              <Ufo />
          </mesh>
      </Suspense>
  </Canvas>
);

useGLTF.preload('/ufo-transformed.glb')
